### ISSUE TITLE
Can not build for device

### ISSUE THREAD

**Issue by alexlarocca** [hansemannn/titanium-context-menu#5]
The plugin works on simulator but app fails to build for device (iPad with iOS 15). Just adding the module to the project.
My env: XCode 13.1, Ti SDK 10.1.0.GA

```
[TRACE] Undefined symbols for architecture arm64:
[TRACE]   "_OBJC_IVAR_$_TiUINavBarButton.activityDelegate", referenced from:
[TRACE]       -[TiUINavBarButton(ContextMenu) initWithProxy:] in libti.contextmenu.a(TiUIBarButtonProxy+ContextMenu.o)
[TRACE]   "_OBJC_IVAR_$_TiUINavBarButton.proxy", referenced from:
[TRACE]       -[TiUINavBarButton(ContextMenu) initWithProxy:] in libti.contextmenu.a(TiUIBarButtonProxy+ContextMenu.o)
[TRACE]   "_OBJC_CLASS_$_TiUIButtonProxy", referenced from:
[TRACE]       __OBJC_$_CATEGORY_TiUIButtonProxy_$_ContextMenu in libti.contextmenu.a(TiUIButtonProxy+ContextMenu.o)
[TRACE]   "_OBJC_CLASS_$_TiUINavBarButton", referenced from:
[TRACE]       __OBJC_$_CATEGORY_TiUINavBarButton_$_ContextMenu in libti.contextmenu.a(TiUIBarButtonProxy+ContextMenu.o)
[TRACE]       l_OBJC_CLASSLIST_SUP_REFS_$_ in libti.contextmenu.a(TiUIBarButtonProxy+ContextMenu.o)
[TRACE]   "_OBJC_CLASS_$_TiUIListView", referenced from:
[TRACE]       __OBJC_$_CATEGORY_TiUIListView_$_ContextMenu in libti.contextmenu.a(TiUIListView+ContextMenu.o)
[TRACE] ld: symbol(s) not found for architecture arm64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
```

**Comment by alexlarocca** [comment]
Build fails since version 2.2.0
It works with 2.1.0 or below

**Comment by hansemannn** [comment]
It requires some UI elements to be used, for example at least one button and one nav button in your project

**Comment by alexlarocca** [comment]
I just use it for Interaction, no UIMenu

**Comment by dlewis23** [comment]
I have this same issue, it works perfect in the simulator but I can not build to device with it. I am using the newest 3.0.1 release. 

It also throws about 50 messages saying...

`[INFO]  Compiler error: Invalid library file`

Not sure where to begin.

**Comment by hansemannn** [comment]
The issue for most users was that they don't use `Ti.UI.ListView` **and** `Ti.UI.TableView` which is required right now, as we're hooking into their native proxies. To workaround, just add an empty `Ti.UI.createListView()` and `Ti.UI.createTableView()` to your app.js / alloy.js to make sure it's symbols are compiled into the app. Thank you!
